# This file was generated by GoReleaser. DO NOT EDIT.
cask "aeolus" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "8501e5bf825201c9f059af26ed15abf0a9b590a135445bf0f7f71b11b609bc1e"
      url "https://github.com/aeolus-labs/aeolus/releases/download/v#{version}/aeolus_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "a4130d18b6b326072b00ad0e4e75e8a10ff87d9255f950fad2f4e24a905a2548"
      url "https://github.com/aeolus-labs/aeolus/releases/download/v#{version}/aeolus_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "bb7a364a0154ba9bb06fc22335fb96a680fadc8dd681f0511e4a9460e34cf451"
      url "https://github.com/aeolus-labs/aeolus/releases/download/v#{version}/aeolus_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "122b602859d3f5ebd8ee79934f83cb35f397b4e0994a390f6f352dd4cd237ee9"
      url "https://github.com/aeolus-labs/aeolus/releases/download/v#{version}/aeolus_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "aeolus"
  desc "Local gateway for Model Context Protocol (MCP) servers"
  homepage "https://github.com/aeolus-labs/aeolus"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aeolus"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aeolus"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Aeolus is installed. To finish setup:

      aeolus service install   # installs the OS service + starts the daemon
      aeolus open              # opens the dashboard at http://localhost:8765

    On Linux, also enable user lingering so the daemon keeps running
    when you're logged out:

      sudo loginctl enable-linger $USER

    Configure MCP servers via the dashboard, or edit:

      ~/.config/aeolus/aeolus.yaml

    Then point Claude / Cursor / Zed / Copilot at Aeolus — the
    dashboard's "Connect a client" button generates the exact snippet
    for each client.
  EOS
end
