# This file was generated by GoReleaser. DO NOT EDIT.
cask "aeolus" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "fd81c4bd564f6199d7a5406a81113fe381add0fe09d3cbe02e2eb13468d71994"
      url "https://github.com/aeolus-labs/aeolus/releases/download/v#{version}/aeolus_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "c76b89c6fc9c9959dc6c29a3b0de268e9fff12c000177ecb5b852b7f0ec65de9"
      url "https://github.com/aeolus-labs/aeolus/releases/download/v#{version}/aeolus_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a4644dea6312d671e75bb7012cdeff2e163d704a6f18e2452782c5a9a2039ae5"
      url "https://github.com/aeolus-labs/aeolus/releases/download/v#{version}/aeolus_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "371c8c2f62f0caad1454a579d5e290335f60a31b8b05600d04b0a48f148e0f76"
      url "https://github.com/aeolus-labs/aeolus/releases/download/v#{version}/aeolus_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "aeolus"
  desc "Local gateway for Model Context Protocol (MCP) servers"
  homepage "https://github.com/aeolus-labs/aeolus"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aeolus"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aeolus"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Aeolus is installed. To finish setup:

      aeolus service install   # installs the OS service + starts the daemon
      aeolus open              # opens the dashboard at http://localhost:8765

    On Linux, also enable user lingering so the daemon keeps running
    when you're logged out:

      sudo loginctl enable-linger $USER

    Configure MCP servers via the dashboard, or edit:

      ~/.config/aeolus/aeolus.yaml

    Then point Claude / Cursor / Zed / Copilot at Aeolus — the
    dashboard's "Connect a client" button generates the exact snippet
    for each client.
  EOS
end
