# This file was generated by GoReleaser. DO NOT EDIT.
cask "aeolus" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "d42a94e7866576137bef6d150fdfc4f66e18a6b679ee48cdf91faceb31e50a76"
      url "https://github.com/aeolus-labs/aeolus/releases/download/v#{version}/aeolus_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "b82638d0eb6898bdfd1c7ecae08a58d280f2e5347a72db46f432c24ca3b24170"
      url "https://github.com/aeolus-labs/aeolus/releases/download/v#{version}/aeolus_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c3c64fa91e2726fb1bd517def64eb9a73990bef9bb206b5b0f13f78693cd1e58"
      url "https://github.com/aeolus-labs/aeolus/releases/download/v#{version}/aeolus_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "87bae91246cb8dd90dc788e90a01e53e89683740b4e06fe9b257a494583dd5f9"
      url "https://github.com/aeolus-labs/aeolus/releases/download/v#{version}/aeolus_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "aeolus"
  desc "Local gateway for Model Context Protocol (MCP) servers"
  homepage "https://github.com/aeolus-labs/aeolus"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aeolus"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aeolus"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Aeolus is installed. To finish setup:

      aeolus service install   # installs the OS service + starts the daemon
      aeolus open              # opens the dashboard at http://localhost:8765

    On Linux, also enable user lingering so the daemon keeps running
    when you're logged out:

      sudo loginctl enable-linger $USER

    Configure MCP servers via the dashboard, or edit:

      ~/.config/aeolus/aeolus.yaml

    Then point Claude / Cursor / Zed / Copilot at Aeolus — the
    dashboard's "Connect a client" button generates the exact snippet
    for each client.
  EOS
end
